spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: clip-curator
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/clipcuratordb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      "[hibernate.format_sql]": true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      repositories:
        enabled: false

app:
  aws:
    region: ${AWS_REGION}
    s3:
      bucket: ${CLIPCURATOR_S3_BUCKET}
  huggingface:
    whisper-url: ${CLIPCURATOR_WHISPER_URL}
    clip-url: ${CLIPCURATOR_CLIP_URL}
  pinecone:
    api-key: ${PINECONE_API_KEY}
    index-name: ${PINECONE_INDEX_NAME}
    namespace: ${PINECONE_NAMESPACE}
  search:
    top-k: ${CLIPCURATOR_SEARCH_TOP_K}
    minimum-score: ${CLIPCURATOR_SEARCH_MINIMUM_SCORE}
  processing:
    tmp-dir: ${CLIPCURATOR_TMP_DIR}
    frame-sampling-fps: ${CLIPCURATOR_FRAME_SAMPLING_FPS}
    ffmpeg:
      command: ${FFMPEG_COMMAND}
    ffprobe:
      command: ${FFPROBE_COMMAND}
