spring:
  application:
    name: clip-curator
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/clipcuratordb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      "[hibernate.format_sql]": true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      repositories:
        enabled: false

app:
  aws:
    region: ${AWS_REGION:us-east-1}
    s3:
      bucket: ${CLIPCURATOR_S3_BUCKET:clip-curator}
  huggingface:
    api-token: local-dev-token
    whisper-url: http://127.0.0.1:8000/models/openai/whisper-large-v3
    clip-url: http://127.0.0.1:8000/pipeline/feature-extraction/sentence-transformers/clip-ViT-B-32
  pinecone:
    api-key: ${PINECONE_API_KEY:pcsk_3sJird_MagRZkwiwuPVdAZhD5JLMC5PvRiejDDTfvpPcNuNoFqeqkq9P5ixNnEpWgeLqQR}
    index-name: ${PINECONE_INDEX_NAME:clip-curator}
    namespace: ${PINECONE_NAMESPACE:__default__}
  search:
    top-k: ${CLIPCURATOR_SEARCH_TOP_K:50}
    minimum-score: ${CLIPCURATOR_SEARCH_MINIMUM_SCORE:0.15}
  processing:
    tmp-dir: ${CLIPCURATOR_TMP_DIR:/tmp/clipcurator/assets}
    frame-sampling-fps: ${CLIPCURATOR_FRAME_SAMPLING_FPS:1.0}
    ffmpeg:
      command: ${FFMPEG_COMMAND:ffmpeg}
